"""Report generation service using ReportLab to generate audit-grade security PDFs."""

from __future__ import annotations

import html
import io
from datetime import UTC, datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.finding import Finding
from app.models.project import Project
from app.models.risk_assessment import RiskAssessment
from app.models.scan import Scan
from app.schemas.report import ComplianceStatus, ReportSummary


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page numbers and running headers."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running header on pages > 1
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, 755, 572, 755)
            self.drawString(40, 760, "CodeSentinel — Executive Security Assessment Report")
            self.drawRightString(572, 760, "CONFIDENTIAL / AUDIT-GRADE")

        # Running footer on all pages
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(40, 42, 572, 42)
        self.drawString(40, 30, "Generated by CodeSentinel Local-First Security Engine")
        self.drawRightString(572, 30, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class ReportService:
    """Service to compute compliance and compile executive PDF reports."""

    @staticmethod
    def get_compliance_benchmarks(
        findings: list[Finding], assessment: RiskAssessment | None
    ) -> list[ComplianceStatus]:
        critical = sum(1 for f in findings if f.severity == "critical")
        high = sum(1 for f in findings if f.severity == "high")
        secret_count = sum(1 for f in findings if f.category == "secrets")
        dep_count = sum(1 for f in findings if f.category == "dependency")
        vuln_count = sum(1 for f in findings if f.category == "vulnerability")

        return [
            ComplianceStatus(
                framework="OWASP Top 10 (2021)",
                score=max(20, 100 - vuln_count * 12),
                status="compliant"
                if vuln_count == 0
                else "warning"
                if vuln_count <= 2
                else "failing",
                violations=vuln_count,
            ),
            ComplianceStatus(
                framework="CWE Top 25 Standards",
                score=max(25, 100 - (critical * 20 + high * 10)),
                status="compliant"
                if critical == 0 and high <= 1
                else "warning"
                if critical <= 1
                else "failing",
                violations=critical + high,
            ),
            ComplianceStatus(
                framework="Secret Hygiene & Credentials",
                score=max(10, 100 - secret_count * 25),
                status="compliant"
                if secret_count == 0
                else "warning"
                if secret_count == 1
                else "failing",
                violations=secret_count,
            ),
            ComplianceStatus(
                framework="SCA / Dependency Health",
                score=max(25, 100 - dep_count * 8),
                status="compliant"
                if dep_count == 0
                else "warning"
                if dep_count <= 3
                else "failing",
                violations=dep_count,
            ),
        ]

    @staticmethod
    def calculate_summary(
        scan: Scan,
        project: Project | None,
        assessment: RiskAssessment | None,
        findings: list[Finding],
    ) -> ReportSummary:
        critical = sum(1 for f in findings if f.severity == "critical")
        high = sum(1 for f in findings if f.severity == "high")
        medium = sum(1 for f in findings if f.severity == "medium")
        low = sum(1 for f in findings if f.severity == "low")

        score = round(assessment.overall_score) if assessment else 75

        if score >= 90:
            grade = "A"
        elif score >= 80:
            grade = "B+"
        elif score >= 70:
            grade = "B-"
        elif score >= 60:
            grade = "C"
        else:
            grade = "F"

        compliance = ReportService.get_compliance_benchmarks(findings, assessment)

        return ReportSummary(
            projectName=project.name if project else "Unknown Project",
            scanId=scan.id,
            generatedAt=scan.completed_at or scan.created_at or datetime.now(UTC),
            overallScore=score,
            grade=grade,
            totalFindings=len(findings) if findings else scan.findings_count,
            criticalCount=critical,
            highCount=high,
            mediumCount=medium,
            lowCount=low,
            compliance=compliance,
        )

    @classmethod
    def generate_pdf_report(
        cls,
        scan: Scan,
        project: Project | None,
        assessment: RiskAssessment | None,
        findings: list[Finding],
    ) -> bytes:
        """Generate an audit-grade PDF security report extracted from scan data."""
        summary = cls.calculate_summary(scan, project, assessment, findings)

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            leftMargin=40,
            rightMargin=40,
            topMargin=45,
            bottomMargin=50,
        )

        base_styles = getSampleStyleSheet()

        # Palette colors matching CodeSentinel design system
        c_primary = colors.HexColor("#7C3AED")
        c_primary_dark = colors.HexColor("#4C1D95")
        c_surface_dark = colors.HexColor("#0F172A")
        c_slate_dark = colors.HexColor("#1E293B")
        c_text_main = colors.HexColor("#334155")
        c_text_muted = colors.HexColor("#64748B")
        c_border = colors.HexColor("#E2E8F0")
        c_bg_light = colors.HexColor("#F8FAFC")

        c_critical = colors.HexColor("#E11D48")
        c_high = colors.HexColor("#EA580C")
        c_medium = colors.HexColor("#D97706")
        c_low = colors.HexColor("#2563EB")
        c_success = colors.HexColor("#16A34A")

        # Custom Typography Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=base_styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=c_surface_dark,
            alignment=0,
        )

        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=c_text_muted,
        )

        section_heading = ParagraphStyle(
            "SectionHeading",
            parent=base_styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=c_slate_dark,
            spaceBefore=14,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "ReportBody",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=c_text_main,
        )

        meta_label = ParagraphStyle(
            "MetaLabel",
            parent=base_styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=c_text_muted,
        )

        meta_val = ParagraphStyle(
            "MetaVal",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=c_surface_dark,
        )

        code_snippet_style = ParagraphStyle(
            "CodeSnippet",
            parent=base_styles["Normal"],
            fontName="Courier",
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#0F172A"),
        )

        remediation_style = ParagraphStyle(
            "RemediationText",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        )

        story: list[Any] = []

        # ==================== HEADER & BRANDING ====================
        brand_table_data = [
            [
                Paragraph(
                    "<b>CODESENTINEL</b>",
                    ParagraphStyle(
                        "BrandLogo",
                        fontName="Helvetica-Bold",
                        fontSize=12,
                        leading=14,
                        textColor=c_primary,
                    ),
                ),
                Paragraph(
                    f"Generated: {summary.generatedAt.strftime('%Y-%m-%d %H:%M:%S UTC')}",
                    ParagraphStyle(
                        "HeaderDate",
                        fontName="Helvetica",
                        fontSize=8,
                        leading=10,
                        alignment=2,
                        textColor=c_text_muted,
                    ),
                ),
            ]
        ]
        brand_table = Table(brand_table_data, colWidths=[266, 266])
        brand_table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        story.append(brand_table)
        story.append(
            HRFlowable(width="100%", thickness=1.5, color=c_primary, spaceBefore=4, spaceAfter=12)
        )

        # Title & Subtitle
        story.append(Paragraph("Security Assessment & Vulnerability Audit Report", title_style))
        story.append(Spacer(1, 3))
        story.append(
            Paragraph(
                "Executive technical synthesis of static application security testing (SAST), "
                "secret detection, and software composition analysis (SCA).",
                subtitle_style,
            )
        )
        story.append(Spacer(1, 12))

        # ==================== TARGET REPOSITORY / PROJECT META ====================
        target_path = (
            project.local_path
            if project and project.local_path
            else (project.repo_url if project and project.repo_url else "Local Workspace")
        )
        meta_table_data = [
            [
                Paragraph("Target Project:", meta_label),
                Paragraph(f"<b>{html.escape(summary.projectName)}</b>", meta_val),
                Paragraph("Scan ID:", meta_label),
                Paragraph(f"#{summary.scanId}", meta_val),
            ],
            [
                Paragraph("Analysis Scope:", meta_label),
                Paragraph(html.escape(str(target_path)), meta_val),
                Paragraph("Status:", meta_label),
                Paragraph(
                    f"<font color='{c_success.hexval()}'><b>{scan.status.upper()}</b></font>",
                    meta_val,
                ),
            ],
            [
                Paragraph("Scan Started:", meta_label),
                Paragraph(
                    scan.started_at.strftime("%Y-%m-%d %H:%M:%S") if scan.started_at else "N/A",
                    meta_val,
                ),
                Paragraph("Completed:", meta_label),
                Paragraph(
                    scan.completed_at.strftime("%Y-%m-%d %H:%M:%S") if scan.completed_at else "N/A",
                    meta_val,
                ),
            ],
        ]
        meta_table = Table(meta_table_data, colWidths=[90, 200, 72, 170])
        meta_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), c_bg_light),
                    ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(meta_table)
        story.append(Spacer(1, 14))

        # ==================== EXECUTIVE RISK POSTURE ====================
        grade_color = (
            c_success
            if summary.grade in ("A", "B+")
            else (c_medium if summary.grade in ("B-", "C") else c_critical)
        )
        grade_cell = [
            Paragraph(
                "SECURITY GRADE",
                ParagraphStyle(
                    "GradeLabel",
                    fontName="Helvetica-Bold",
                    fontSize=8,
                    leading=9,
                    textColor=c_text_muted,
                    alignment=1,
                ),
            ),
            Spacer(1, 4),
            Paragraph(
                f"<b>{summary.grade}</b>",
                ParagraphStyle(
                    "GradeVal",
                    fontName="Helvetica-Bold",
                    fontSize=32,
                    leading=34,
                    textColor=grade_color,
                    alignment=1,
                ),
            ),
            Spacer(1, 2),
            Paragraph(
                f"Risk Score: <b>{summary.overallScore}/100</b>",
                ParagraphStyle(
                    "GradeScore",
                    fontName="Helvetica-Bold",
                    fontSize=8.5,
                    leading=10,
                    textColor=c_text_main,
                    alignment=1,
                ),
            ),
        ]

        metrics_cell = [
            Paragraph(
                "FINDINGS SEVERITY DISTRIBUTION",
                ParagraphStyle(
                    "DistLabel",
                    fontName="Helvetica-Bold",
                    fontSize=8,
                    leading=9,
                    textColor=c_text_muted,
                ),
            ),
            Spacer(1, 6),
            Table(
                [
                    [
                        Paragraph(
                            f"<font color='{c_critical.hexval()}'><b>CRITICAL</b></font>",
                            ParagraphStyle(
                                "Scrit",
                                fontName="Helvetica-Bold",
                                fontSize=8,
                                leading=9,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_high.hexval()}'><b>HIGH</b></font>",
                            ParagraphStyle(
                                "Shigh",
                                fontName="Helvetica-Bold",
                                fontSize=8,
                                leading=9,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_medium.hexval()}'><b>MEDIUM</b></font>",
                            ParagraphStyle(
                                "Smed",
                                fontName="Helvetica-Bold",
                                fontSize=8,
                                leading=9,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_low.hexval()}'><b>LOW</b></font>",
                            ParagraphStyle(
                                "Slow",
                                fontName="Helvetica-Bold",
                                fontSize=8,
                                leading=9,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            "<b>TOTAL</b>",
                            ParagraphStyle(
                                "Stot",
                                fontName="Helvetica-Bold",
                                fontSize=8,
                                leading=9,
                                alignment=1,
                            ),
                        ),
                    ],
                    [
                        Paragraph(
                            f"<font color='{c_critical.hexval()}'>"
                            f"<b>{summary.criticalCount}</b></font>",
                            ParagraphStyle(
                                "Vcrit",
                                fontName="Helvetica-Bold",
                                fontSize=15,
                                leading=17,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_high.hexval()}'><b>{summary.highCount}</b></font>",
                            ParagraphStyle(
                                "Vhigh",
                                fontName="Helvetica-Bold",
                                fontSize=15,
                                leading=17,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_medium.hexval()}'>"
                            f"<b>{summary.mediumCount}</b></font>",
                            ParagraphStyle(
                                "Vmed",
                                fontName="Helvetica-Bold",
                                fontSize=15,
                                leading=17,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<font color='{c_low.hexval()}'><b>{summary.lowCount}</b></font>",
                            ParagraphStyle(
                                "Vlow",
                                fontName="Helvetica-Bold",
                                fontSize=15,
                                leading=17,
                                alignment=1,
                            ),
                        ),
                        Paragraph(
                            f"<b>{summary.totalFindings}</b>",
                            ParagraphStyle(
                                "Vtot",
                                fontName="Helvetica-Bold",
                                fontSize=15,
                                leading=17,
                                alignment=1,
                            ),
                        ),
                    ],
                ],
                colWidths=[70, 70, 70, 70, 76],
            ),
        ]

        posture_table = Table([[grade_cell, metrics_cell]], colWidths=[160, 372])
        posture_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                    ("BOX", (0, 0), (-1, -1), 1, c_border),
                    ("LINEBEFORE", (1, 0), (1, 0), 1, c_border),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(posture_table)
        story.append(Spacer(1, 14))

        # ==================== STANDARDS & COMPLIANCE BENCHMARKS ====================
        story.append(Paragraph("Standards & Compliance Benchmarks", section_heading))
        comp_rows = [
            [
                Paragraph("<b>Framework / Benchmark</b>", meta_label),
                Paragraph(
                    "<b>Posture Score</b>", ParagraphStyle("h_sc", parent=meta_label, alignment=1)
                ),
                Paragraph(
                    "<b>Compliance Status</b>",
                    ParagraphStyle("h_st", parent=meta_label, alignment=1),
                ),
                Paragraph(
                    "<b>Rule Violations</b>", ParagraphStyle("h_v", parent=meta_label, alignment=1)
                ),
            ]
        ]
        for c in summary.compliance:
            stat_color = (
                c_success
                if c.status == "compliant"
                else (c_medium if c.status == "warning" else c_critical)
            )
            comp_rows.append(
                [
                    Paragraph(f"<b>{html.escape(c.framework)}</b>", body_style),
                    Paragraph(
                        f"<b>{c.score}%</b>", ParagraphStyle("v_sc", parent=body_style, alignment=1)
                    ),
                    Paragraph(
                        f"<font color='{stat_color.hexval()}'><b>{c.status.upper()}</b></font>",
                        ParagraphStyle("v_st", parent=body_style, alignment=1),
                    ),
                    Paragraph(
                        f"<b>{c.violations}</b> issues",
                        ParagraphStyle("v_v", parent=body_style, alignment=1),
                    ),
                ]
            )
        comp_table = Table(comp_rows, colWidths=[232, 100, 100, 100])
        comp_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), c_bg_light),
                    ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(comp_table)
        story.append(Spacer(1, 16))

        # ==================== DETAILED FINDINGS CATALOG ====================
        story.append(PageBreak())  # Start findings catalog on Page 2
        story.append(Paragraph("Detailed Security Findings Catalog", section_heading))
        story.append(
            Paragraph(
                f"The scan extracted {len(findings)} distinct findings across static analysis, "
                "secrets scanning, and SCA. Prioritized below by severity rank.",
                subtitle_style,
            )
        )
        story.append(Spacer(1, 10))

        # Separate findings by category for structured presentation
        vuln_findings = [f for f in findings if f.category == "vulnerability"]
        secret_findings = [f for f in findings if f.category == "secrets"]
        config_findings = [f for f in findings if f.category in ("configuration", "repository")]
        dep_findings = [f for f in findings if f.category == "dependency"]

        # 1. Code Vulnerabilities (SAST & AST)
        if vuln_findings:
            story.append(
                Paragraph(
                    f"1. Static Code Analysis (SAST) Flaws ({len(vuln_findings)} items)",
                    ParagraphStyle(
                        "SubSec1",
                        parent=section_heading,
                        fontSize=11,
                        spaceBefore=8,
                        spaceAfter=4,
                        textColor=c_primary_dark,
                    ),
                )
            )
            for f in vuln_findings:
                story.append(
                    cls._build_finding_block(
                        f,
                        c_critical,
                        c_high,
                        c_medium,
                        c_low,
                        c_border,
                        c_bg_light,
                        meta_label,
                        meta_val,
                        body_style,
                        code_snippet_style,
                        remediation_style,
                    )
                )
                story.append(Spacer(1, 8))

        # 2. Secret Exposure Findings
        if secret_findings:
            story.append(
                Paragraph(
                    f"2. Credential & Secret Exposures ({len(secret_findings)} items)",
                    ParagraphStyle(
                        "SubSec2",
                        parent=section_heading,
                        fontSize=11,
                        spaceBefore=10,
                        spaceAfter=4,
                        textColor=c_primary_dark,
                    ),
                )
            )
            for f in secret_findings:
                story.append(
                    cls._build_finding_block(
                        f,
                        c_critical,
                        c_high,
                        c_medium,
                        c_low,
                        c_border,
                        c_bg_light,
                        meta_label,
                        meta_val,
                        body_style,
                        code_snippet_style,
                        remediation_style,
                    )
                )
                story.append(Spacer(1, 8))

        # 3. Configuration Findings
        if config_findings:
            story.append(
                Paragraph(
                    f"3. Configuration & Repository Security ({len(config_findings)} items)",
                    ParagraphStyle(
                        "SubSec3",
                        parent=section_heading,
                        fontSize=11,
                        spaceBefore=10,
                        spaceAfter=4,
                        textColor=c_primary_dark,
                    ),
                )
            )
            for f in config_findings:
                story.append(
                    cls._build_finding_block(
                        f,
                        c_critical,
                        c_high,
                        c_medium,
                        c_low,
                        c_border,
                        c_bg_light,
                        meta_label,
                        meta_val,
                        body_style,
                        code_snippet_style,
                        remediation_style,
                    )
                )
                story.append(Spacer(1, 8))

        # 4. Dependency Findings (SCA) — format as structured table to avoid 50 pages of repetition
        if dep_findings:
            dep_heading = (
                f"4. Software Composition Analysis (SCA) Dependencies ({len(dep_findings)} items)"
            )
            story.append(
                Paragraph(
                    dep_heading,
                    ParagraphStyle(
                        "SubSec4",
                        parent=section_heading,
                        fontSize=11,
                        spaceBefore=10,
                        spaceAfter=4,
                        textColor=c_primary_dark,
                    ),
                )
            )
            story.append(
                Paragraph(
                    "Third-party manifest dependencies identified with known vulnerabilities "
                    "or insecure version pinning.",
                    subtitle_style,
                )
            )
            story.append(Spacer(1, 6))

            dep_table_data = [
                [
                    Paragraph("<b>Advisory / Rule</b>", meta_label),
                    Paragraph("<b>Manifest File</b>", meta_label),
                    Paragraph(
                        "<b>Severity</b>", ParagraphStyle("h_sev", parent=meta_label, alignment=1)
                    ),
                    Paragraph("<b>Recommended Action</b>", meta_label),
                ]
            ]
            for df in dep_findings[:40]:  # Present top 40 dependencies cleanly
                s_color = (
                    c_critical
                    if df.severity == "critical"
                    else (
                        c_high
                        if df.severity == "high"
                        else (c_medium if df.severity == "medium" else c_low)
                    )
                )
                file_short = df.file.split("/")[-1] if df.file else "manifest"
                r_id = html.escape(df.rule_id or "OSV/SCA")
                title_html = (
                    f"<b>{html.escape(df.title)}</b><br/>"
                    f"<font color='#64748B' size='6.5'>{r_id}</font>"
                )
                pkg_rem = html.escape(
                    df.remediation or "Pin and upgrade package to latest secure release."
                )
                remed_html = f"<font size='7'>{pkg_rem}</font>"
                dep_table_data.append(
                    [
                        Paragraph(title_html, body_style),
                        Paragraph(f"<font size='7'>{html.escape(file_short)}</font>", body_style),
                        Paragraph(
                            f"<font color='{s_color.hexval()}'><b>{df.severity.upper()}</b></font>",
                            ParagraphStyle("d_sev", parent=body_style, alignment=1),
                        ),
                        Paragraph(remed_html, body_style),
                    ]
                )

            if len(dep_findings) > 40:
                omitted_count = len(dep_findings) - 40
                dep_table_data.append(
                    [
                        Paragraph(
                            f"<i>... and {omitted_count} additional dependency items omitted.</i>",
                            body_style,
                        ),
                        Paragraph("", body_style),
                        Paragraph("", body_style),
                        Paragraph("", body_style),
                    ]
                )

            dep_table = Table(dep_table_data, colWidths=[160, 110, 62, 200])
            dep_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), c_bg_light),
                        ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ]
                )
            )
            story.append(dep_table)
            story.append(Spacer(1, 14))

        # ==================== LOCAL-FIRST AUDIT INTEGRITY STATEMENT ====================
        story.append(Spacer(1, 10))
        audit_note = Table(
            [
                [
                    Paragraph(
                        "<b>LOCAL-FIRST AUDIT INTEGRITY GUARANTEE</b>",
                        ParagraphStyle(
                            "AuditH",
                            fontName="Helvetica-Bold",
                            fontSize=8,
                            leading=10,
                            textColor=c_primary,
                        ),
                    ),
                ],
                [
                    Paragraph(
                        "This security assessment was executed locally on host infrastructure "
                        "by the CodeSentinel analysis pipeline. No proprietary source code "
                        "was exfiltrated to cloud hosting environments or third-party servers.",
                        ParagraphStyle(
                            "AuditP",
                            fontName="Helvetica",
                            fontSize=7.5,
                            leading=10,
                            textColor=c_text_muted,
                        ),
                    ),
                ],
            ],
            colWidths=[532],
        )
        audit_note.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), c_bg_light),
                    ("BOX", (0, 0), (-1, -1), 1, c_border),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ]
            )
        )
        story.append(KeepTogether([audit_note]))

        # Build PDF with dynamic NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        return buf.getvalue()

    @classmethod
    def _build_finding_block(
        cls,
        f: Finding,
        c_critical: colors.Color,
        c_high: colors.Color,
        c_medium: colors.Color,
        c_low: colors.Color,
        c_border: colors.Color,
        c_bg_light: colors.Color,
        meta_label: ParagraphStyle,
        meta_val: ParagraphStyle,
        body_style: ParagraphStyle,
        code_snippet_style: ParagraphStyle,
        remediation_style: ParagraphStyle,
    ) -> KeepTogether:
        """Build an elegant, self-contained flowable card for a single security finding."""
        s_color = (
            c_critical
            if f.severity == "critical"
            else (
                c_high if f.severity == "high" else (c_medium if f.severity == "medium" else c_low)
            )
        )

        # Title row
        title_html = (
            f"<font color='{s_color.hexval()}'><b>[{f.severity.upper()}]</b></font> "
            f"<b>{html.escape(f.title)}</b>"
        )
        title_para = Paragraph(
            title_html,
            ParagraphStyle(
                "FTitle",
                fontName="Helvetica-Bold",
                fontSize=9.5,
                leading=13,
                textColor=colors.HexColor("#0F172A"),
            ),
        )

        rule_badge_html = (
            f"<font size='7' color='#64748B'>Rule: {html.escape(f.rule_id or 'Custom')} | "
            f"Analyzer: {html.escape(f.analyzer.capitalize())}</font>"
        )
        rule_badge = Paragraph(
            rule_badge_html,
            ParagraphStyle("FRule", fontName="Helvetica", fontSize=7.5, leading=9, alignment=2),
        )

        loc_text = f"{html.escape(f.file)}"
        if f.line_start is not None:
            loc_text += f":{f.line_start}"
            if f.line_end is not None and f.line_end != f.line_start:
                loc_text += f"-{f.line_end}"

        loc_para = Paragraph(
            f"<b>Location:</b> <font face='Courier' size='7.5'>{loc_text}</font>", body_style
        )

        card_elements: list[Any] = [
            Table(
                [[title_para, rule_badge]],
                colWidths=[360, 162],
                style=[
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ],
            ),
            loc_para,
            Spacer(1, 3),
        ]

        if f.description:
            desc_para = Paragraph(html.escape(f.description), body_style)
            card_elements.append(desc_para)
            card_elements.append(Spacer(1, 4))

        # Code snippet block if available
        if f.code_snippet and f.code_snippet.strip():
            snippet_clean = f.code_snippet.strip()
            # Truncate overly long snippets to 8 lines for PDF readability
            lines = snippet_clean.splitlines()[:8]
            escaped_code = "<br/>".join(
                [html.escape(line).replace(" ", "&nbsp;") for line in lines]
            )
            code_table = Table([[Paragraph(escaped_code, code_snippet_style)]], colWidths=[512])
            code_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ]
                )
            )
            card_elements.append(code_table)
            card_elements.append(Spacer(1, 4))

        # Remediation block
        remed_text = f.remediation or (
            "Follow OWASP/CWE remediation guidelines and secure coding standards for this pattern."
        )
        remed_table = Table(
            [[Paragraph(f"<b>Remediation:</b> {html.escape(remed_text)}", remediation_style)]],
            colWidths=[512],
        )
        remed_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F3FF")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDD6FE")),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        card_elements.append(remed_table)

        outer_card = Table([[card_elements]], colWidths=[532])
        outer_card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                    ("BOX", (0, 0), (-1, -1), 0.5, c_border),
                    ("LINELEFT", (0, 0), (0, 0), 3.0, s_color),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        return KeepTogether([outer_card])
